### ISSUE TITLE
Game Requests

### ISSUE THREAD

**Issue by SuperWillow** [ninstar/Rich-Presence-U-DB#33]
Tetris® Forever
PONG Quest
Berzerk: Recharged
SEGA AGES Virtua Racing
G-MODE Archives25 Topolon
SEGA AGES Columns II: A Voyage Through Time
Space Invaders Invincible Collection
de Blob
de Blob 2
Arkanoid: Eternal Battle
Atari Flashback Classics
Hexceed
Wobbledogs
Atari 50: The Anniversary Celebration
Ōkami HD
We Are Doomed
Monomals
Part Time UFO
BOXBOY!+BOXGIRL!
Namco Museum
SEGA AGES Puyo Puyo
SEGA AGES Puyo Puyo 2
Puyo Puyo Champions
PC Building Simulator
Fledgling Heroes
Atari Mania
Tempest 4000

**Comment by ninstar** [comment]
Done.

Some of the requested games were already in the database.

On future requests I recommend specifying which one of the 3 platforms (Wii U, 3DS, Switch) the requests are for, this will help with the addition process.

**Comment by SuperWillow** [comment]
@ninstar Where is Puyo Puyo Champions, you forgot it?

**Comment by SuperWillow** [comment]
@ninstar Thanks for adding the games, but where is Puyo Puyo Champions? And by the way, are these game icons from my list accidentally photographed by me, or do you think you accidentally don't buy these games? And here, by the way, about Puyo Puyo Champions: Why isn't he here?

**Comment by ninstar** [comment]
> [@ninstar](https://github.com/ninstar) Thanks for adding the games, but where is Puyo Puyo Champions? And by the way, are these game icons from my list accidentally photographed by me, or do you think you accidentally don't buy these games? And here, by the way, about Puyo Puyo Champions: Why isn't he here?

It is there, it was add long before this request was made:

- https://github.com/ninstar/Rich-Presence-U-DB/blob/main/titles/hac.csv#L506

![Image](https://github.com/user-attachments/assets/7b744b48-d7b7-4e98-b2ca-a17c91fb6923)
![Image](https://github.com/user-attachments/assets/5eead8fe-6e49-4923-84a3-03fce4a57767)

Have you updated your app and database? The main branch (the one being maintained) only supports Rich Presence U version 1.3.0 and later, there is a separate branch that serves as a snapshot for versions 1.2.3 and older, it is no longer updated but it already included the game you are looking for:

- https://github.com/ninstar/Rich-Presence-U-DB/blob/v123/titles/hac.csv#L492

**Comment by SuperWillow** [comment]
I don't have this program, unfortunately. @ninstar you forgot Namco Museum, add it here too. And by the way, were these game icons photographed by me for a reason, and where was the copy of Tetris Forever purchased?

**Comment by SuperWillow** [comment]
And by the way, to the activity of this game it is necessary to add the following:
![IMG-20240713-WA0008.jpg](https://github.com/user-attachments/assets/bdd874f3-4328-4a73-ad49-60df1873f750)

**Comment by ninstar** [comment]
> I don't have this program, unfortunately. [@ninstar](https://github.com/ninstar) you forgot Namco Museum and Ōkami HD, add it here too.

Well, the database as designed specifically for Rich Presence U, I'm aware some other projects use it as well but I cannot guarantee compatibility or specific features as I'm not the one handling them.

Namco Museum and Ōkami HD are already in the database, just like Puyo Puyo Champions (Ōkami specifically has no punctuation there, it is listed as "OKAMI HD").


>  And by the way, were these game icons photographed by me for a reason, and where was the copy of Tetris Forever purchased? And by the way, thanks for adding Puyo Puyo Champions.

I'm not entirely sure about this question, I don't see any icons attached to your request, normally when this happen I look for them myself, most of the time via the Nintendo eShop or Google.

**Comment by SuperWillow** [comment]
> > I don't have this program, unfortunately. [@ninstar](https://github.com/ninstar) you forgot Namco Museum and Ōkami HD, add it here too.
> 
> Well, the database was designed specifically for Rich Presence U, I'm aware some other projects use it as well but I cannot guarantee compatibility or specific features for those, as I'm not the one handling them.
> 
> Namco Museum and Ōkami HD are already in the database, just like Puyo Puyo Champions (Ōkami specifically has no punctuation there, it is listed as "OKAMI HD").
> 
> 
> >  And by the way, were these game icons photographed by me for a reason, and where was the copy of Tetris Forever purchased? And by the way, thanks for adding Puyo Puyo Champions.
> 
> I'm not entirely sure about this question, I don't see any icons attached to your request, normally when this happen I look for them myself, most of the time via the Nintendo eShop or Google.

I think Ōkami HD and Namco Museum already exist, which I think. Therefore, you don’t need to add them!

**Comment by SuperWillow** [comment]
@ninstar I can show you the icons of these games now, but only those that have already been added:
![IMG_20250223_010138.jpg](https://github.com/user-attachments/assets/fef42e1e-3557-428b-949e-e75496f0157a)
![IMG_20250223_010148.jpg](https://github.com/user-attachments/assets/624069b5-be05-446a-a249-0e6f6d2c8b87)
![IMG_20250223_010206.jpg](https://github.com/user-attachments/assets/27bf5d23-e2b0-4def-be1b-90572107b27b)
![IMG_20250223_010227.jpg](https://github.com/user-attachments/assets/864a7fab-1c89-4d44-a5f7-2c52fea84fb3)
![IMG_20250223_010245.jpg](https://github.com/user-attachments/assets/cdf10308-099c-4d93-9c65-52753765ad65)
![IMG_20250223_010305.jpg](https://github.com/user-attachments/assets/93ceb416-22ec-49df-8e94-30d0fadbe7ea)

And by the way, @ninstar Can you tell me where all these games were bought and where their icons were found? And if I'm talking about the official Nintendo website, look at the [link to Tetris Forever](https://www.nintendo.com/en-ca/store/products/tetris-forever-switch/), it will definitely say that the game has been purchased. I already bought the game from the moment of pre-order.

P.S. I don’t speak English because I have poor knowledge of it. That's why I use my translator.

**Comment by ninstar** [comment]
> [@ninstar](https://github.com/ninstar) I can show you the icons of these games now, but only those that have already been 

I already have them in the database.

> And by the way, [@ninstar](https://github.com/ninstar) Can you tell me where all these games were bought and where their icons were found? And if I'm talking about the official Nintendo website, look at the [link to Tetris Forever](https://www.nintendo.com/en-ca/store/products/tetris-forever-switch/), it will definitely say that the game has been purchased. I already bought the game from the moment of pre-order.

I explained where I find the icons in my previous comment. As for what the Nintendo website shows, it depends on your own account, I didn't purchase these on my account so it shows as not purchased for me.

**Comment by SuperWillow** [comment]
But it seems to me that even if I go to the eShop myself and at least look at the wish list and scroll to where Tetris Forever was purchased, I see an inscription on the right:
![Screenshot_20250223_030749.jpg](https://github.com/user-attachments/assets/4b396df0-4855-4b6a-9c75-1793a826fdce)
@ninstar Do you by any chance have a purchased copy of it?
